/**
 * Who Is King API document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { GameAnswers } from './gameAnswers';

export class Game {
    'uid'?: string;
    'question'?: string;
    'answers'?: Array<GameAnswers>;
    'votes'?: number;
    'openTime'?: Date;
    'closeTime'?: Date;
    'changeToGuessTime'?: Date;
    'currentTime'?: Date;
    'category'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "uid",
            "baseName": "uid",
            "type": "string"
        },
        {
            "name": "question",
            "baseName": "question",
            "type": "string"
        },
        {
            "name": "answers",
            "baseName": "answers",
            "type": "Array<GameAnswers>"
        },
        {
            "name": "votes",
            "baseName": "votes",
            "type": "number"
        },
        {
            "name": "openTime",
            "baseName": "openTime",
            "type": "Date"
        },
        {
            "name": "closeTime",
            "baseName": "closeTime",
            "type": "Date"
        },
        {
            "name": "changeToGuessTime",
            "baseName": "changeToGuessTime",
            "type": "Date"
        },
        {
            "name": "currentTime",
            "baseName": "currentTime",
            "type": "Date"
        },
        {
            "name": "category",
            "baseName": "category",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Game.attributeTypeMap;
    }
}

