/**
 * Who Is King API document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class Game {
    'uid': string;
    'question': string;
    'questionType': string;
    'options': string;
    'points': number;
    'openTime': Date;
    'closeTime': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "uid",
            "baseName": "uid",
            "type": "string"
        },
        {
            "name": "question",
            "baseName": "question",
            "type": "string"
        },
        {
            "name": "questionType",
            "baseName": "questionType",
            "type": "string"
        },
        {
            "name": "options",
            "baseName": "options",
            "type": "string"
        },
        {
            "name": "points",
            "baseName": "points",
            "type": "number"
        },
        {
            "name": "openTime",
            "baseName": "openTime",
            "type": "Date"
        },
        {
            "name": "closeTime",
            "baseName": "closeTime",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return Game.attributeTypeMap;
    }
}

