/**
 * Who Is King API document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { CityResult } from './cityResult';
import { UserResult } from './userResult';

export class InlineResponse2003 {
    'cityResult': Array<CityResult>;
    'userResult': Array<UserResult>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "cityResult",
            "baseName": "cityResult",
            "type": "Array<CityResult>"
        },
        {
            "name": "userResult",
            "baseName": "userResult",
            "type": "Array<UserResult>"
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse2003.attributeTypeMap;
    }
}

