/**
 * Who Is King API document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class InlineResponse200 {
    'uid': string;
    'openTime': Date;
    'closeTime': Date;
    'currentTime': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "uid",
            "baseName": "uid",
            "type": "string"
        },
        {
            "name": "openTime",
            "baseName": "openTime",
            "type": "Date"
        },
        {
            "name": "closeTime",
            "baseName": "closeTime",
            "type": "Date"
        },
        {
            "name": "currentTime",
            "baseName": "currentTime",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse200.attributeTypeMap;
    }
}

