/* tslint:disable */


/**
 * AUTO-GENERATED FILE @ 2020-03-18 22:23:06 - DO NOT EDIT!
 *
 * This file was automatically generated by schemats v.3.0.3
 * $ schemats generate -c postgres://username:password@wikdev.cxejqr4qverc.eu-central-1.rds.amazonaws.com:5432/wik?ssl=true -t User -s public
 *
 */


export namespace UserFields {
    export type uid = string;
    export type fireBaseId = string;
    export type cityId = string | null;

}

export interface User {
    uid: UserFields.uid;
    fireBaseId: UserFields.fireBaseId;
    cityId: UserFields.cityId;

}
